Romelchenko oop - Push homework5 files to master branch
toleksyn/aqa-python-project pull request #12
Opened 2023-04-18 13:27 UTC by RomanO-qa

2023-04-27 07:28 UTC, toleksyn requested changes

2023-04-27 07:28 UTC, toleksyn commented on Bank/bank.py
> +    def all_bank_accounts(self, account):
rename

2023-04-27 07:28 UTC, toleksyn commented on Bank/bank.py
> +    def find_account(self, account_number):
rename

2023-04-27 07:28 UTC, toleksyn commented on Bank/bank.py
> +    def total_interests_earned(self):
rename

2023-04-27 07:37 UTC, RomanO-qa commented on Bank/bank.py
> +    def all_bank_accounts(self, account):
renamed to bank_info

2023-04-27 07:37 UTC, RomanO-qa commented on Bank/bank.py
> +    def total_interests_earned(self):
renamed to earned_interests

2023-05-04 07:15 UTC, toleksyn requested changes

2023-05-04 07:15 UTC, toleksyn commented on Bank/account.py
> +        print("Deposit money!")
should probably use a member variable and store deposit amount there

2023-05-04 09:49 UTC, toleksyn commented on Bank/account.py
> +    def deposit_money(self):
deposit_money(sum)

2023-05-25 07:48 UTC, closed without merging