Igor Kovalenko: Create an instance of the Restaurant class and add a …
toleksyn/aqa-python-project pull request #16
Opened 2023-04-25 21:37 UTC by Igrekonko

…few orders with multiple items each

2023-04-26 10:34 UTC, RomanO-qa approved these changes

2023-04-27 07:32 UTC, toleksyn requested changes

2023-04-27 07:32 UTC, toleksyn commented on restaurant_ordering_system_IKovalenko/appetizer.py
> +
no extra lines

2023-04-27 07:32 UTC, toleksyn commented on restaurant_ordering_system_IKovalenko/main_instance.py
> +drink1 = Drink("Juice", 12.30, "Natural juices in the assortement", "Medium", True)
rename, avoid 1,2 in variable names

2023-05-04 07:19 UTC, toleksyn requested changes

2023-05-04 07:19 UTC, toleksyn commented on restaurant_ordering_system_IKovalenko/main_instance.py
> +order1 = Order(1)
first_order

2023-05-04 07:19 UTC, toleksyn commented on restaurant_ordering_system_IKovalenko/main_instance.py
> +for table_number, order in orders.items():
maybe makes sense to add print_orders(table_number) function to the Restaurant class?

2023-05-25 07:50 UTC, closed without merging