Romelchenko - Added restaurant homework
toleksyn/aqa-python-project pull request #19
Opened 2023-04-26 11:10 UTC by RomanO-qa

2023-04-27 07:34 UTC, toleksyn requested changes

2023-04-27 07:45 UTC, RomanO-qa commented on Omelchenko_Homework6/Restaurant/order.py
> +            items.append(item.name)
updated

2023-04-27 09:37 UTC, toleksyn requested changes

2023-04-27 09:37 UTC, toleksyn commented on Omelchenko_Homework6/Restaurant/drink.py
> +class Drink(MenuItem):
some comment

2023-05-04 07:20 UTC, toleksyn approved these changes

2023-05-04 07:45 UTC, Igrekonko approved these changes

2023-05-25 07:51 UTC, closed without merging