MDonyk Added restaurant task
toleksyn/aqa-python-project pull request #20
Opened 2023-04-26 17:19 UTC by MDonyk

2023-04-27 07:26 UTC, toleksyn approved these changes

2023-04-27 07:29 UTC, RomanO-qa approved these changes

2023-05-04 07:13 UTC, toleksyn requested changes

2023-05-04 07:13 UTC, toleksyn commented on restaurant/main.py
> +order1 = Order(1) # Table number is 1
rename, first_table_order etc

2023-05-25 07:51 UTC, closed without merging