Added Selene homework
toleksyn/aqa-python-project pull request #23
Opened 2023-05-10 08:54 UTC by RomanO-qa

2023-05-10 20:25 UTC, Igrekonko approved these changes

2023-05-11 09:06 UTC, toleksyn requested changes

2023-05-11 09:06 UTC, toleksyn commented on Omelchenko_Selene_Task/selene_test.py
> +assert "Google" == browser.title(), f"Your are not on the Google Homepage"
reconsider title check

2023-05-18 08:50 UTC, toleksyn requested changes

2023-05-18 08:50 UTC, toleksyn commented on Omelchenko_Selene_Task/selene_test.py
> +browser.element(by.xpath("//form/div[1]/div[1]/div[4]/center/input[2]"))
lines 13-15 do nothing

2023-05-25 07:34 UTC, toleksyn requested changes

2023-05-25 07:34 UTC, toleksyn commented on Omelchenko_Selene_Task/selene_test.py
> +browser.element(by.xpath("//form/div[1]/div[1]/div[4]/center/input[2]")).should(be.clickable)
optimize locators

2023-05-25 07:52 UTC, closed without merging