Romelchenko - rozetka Homework
toleksyn/aqa-python-project pull request #24
Opened 2023-05-16 08:49 UTC by RomanO-qa

2023-05-16 20:07 UTC, Igrekonko approved these changes

2023-05-18 08:48 UTC, toleksyn requested changes

2023-05-18 08:48 UTC, toleksyn commented on Omelchenko_Rozetka_Test/find_dell_test.py
> +browser.element(by.xpath("//rz-grid/ul/li[5]/rz-catalog-tile"
optimize locators

2023-05-18 08:48 UTC, toleksyn commented on Omelchenko_Rozetka_Test/find_iphone_test.py
> +                                               "/div/div[2]/div[4]/div[2]/p/span")).text
optimize locators

2023-05-18 08:50 UTC, toleksyn requested changes

2023-05-18 08:50 UTC, toleksyn commented on Omelchenko_Rozetka_Test/open_login_test.py
> +browser.element(by.xpath("//rz-top-slider/ul/li/a")).should(have.text("Всі акції"))
avoid using cyrillic in assertions

2023-05-25 07:35 UTC, toleksyn approved these changes

2023-05-25 07:53 UTC, closed without merging